#!/bin/bash

#ddev-generated

## Description: Run backstopjs
## Usage: backstopjs [args]
## Example: "ddev backstopjs version"
## ExecRaw: true

if [ "$1" == "openReport" -o "$1" == "remote" ]; then
  echo "This does not work for backstop in ddev"
  exit 1
fi

cd /src/tests/functional/backstopjs
NODE_PATH="/usr/local/lib/node_modules/" backstop "$@"
